method: onet
data:
  path: /data/c/jisan/Datasets/LearnedReconstructionDatasets/ShapeNetFull/ShapeNet_Onet
  img_folder: img_choy2016
  img_size: 224 
  points_subsample: 2048 
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: resnet18
  c_dim: 256
  z_dim: 0
training:
  out_dir: /data/c/jisan/NetworkModels/LearnedReconstruction/ObjectReconstructionOnetBased/SingleView/DirectONet
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
#  visualize_every: 20
  visualize_every: 2000
  validate_every: 5000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

